apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: job
  namespace: playground
spec:
  chart:
    git: https://github.com/vdonadze/job-chart
    path: chart
    ref: main
    skipDepUpdate: true
  forceUpgrade: false
  releaseName: playground-job
  resetValues: true
  wait: false