apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: job
  namespace: playground
spec:
  chart:
    git: https://github.com/vdonadze/job-chart
    path: chart
    ref: main
  values:
    annotations: playground/job
    component:
      image: nexus.exactpro.com:16000/giorgi.mania/env-printer:1.0.1
      name: printer