apiVersion: batch/v1
kind: Job
metadata:
  name: test-job
spec:
  backoffLimit: 0
  template:
    metadata:
      name: test-job
    spec:
      containers:
        - name: {{ .Values.name }}
          image: {{ .Values.image }}
      imagePullSecrets:
        - name: th2-core
        - name: th2-solution
      restartPolicy: Never
