apiVersion: batch/v1
kind: Job
metadata:
  name: test-job
spec:
  backoffLimit: 0
  template:
    metadata:
      name: test-job
    spec:
      containers:
        - name: printer
          image: nexus.exactpro.com:16000/giorgi.mania/env-printer:1.0.1
      imagePullSecrets:
        - name: th2-core
        - name: th2-solution
      restartPolicy: Never
